In [1]:
import zipfile

# Unzip once to create your project structure
with zipfile.ZipFile('Initial_data_points_starter.zip', 'r') as zip_ref:
    zip_ref.extractall('capstone_data')

In [2]:
import zipfile
import os

# 1. Unzip the file
zip_filename = 'Initial_data_points_starter.zip'  # Replace with your actual filename
extract_path = 'capstone_data'

with zipfile.ZipFile(zip_filename, 'r') as zip_ref:
    zip_ref.extractall(extract_path)
    print(f"--- Files extracted to: {extract_path} ---\n")

# 2. Map out the folder structure
for root, dirs, files in os.walk(extract_path):
    level = root.replace(extract_path, '').count(os.sep)
    indent = ' ' * 4 * (level)
    print(f"{indent}{os.path.basename(root)}/")
    sub_indent = ' ' * 4 * (level + 1)
    for f in files:
        if f.endswith('.npy'):
            print(f"{sub_indent}📄 {f}")

--- Files extracted to: capstone_data ---

capstone_data/
    initial_data/
        function_1/
            📄 initial_inputs.npy
            📄 initial_outputs.npy
            .ipynb_checkpoints/
        function_2/
            📄 initial_inputs.npy
            📄 initial_outputs.npy
        function_3/
            📄 initial_inputs.npy
            📄 initial_outputs.npy
        function_4/
            📄 initial_inputs.npy
            📄 initial_outputs.npy
        function_5/
            📄 initial_inputs.npy
            📄 initial_outputs.npy
        function_6/
            📄 initial_inputs.npy
            📄 initial_outputs.npy
        function_7/
            📄 initial_inputs.npy
            📄 initial_outputs.npy
        function_8/
            📄 initial_inputs.npy
            📄 initial_outputs.npy
    __MACOSX/
        initial_data/


In [3]:
import numpy as np
import os

base_path = 'capstone_data/initial_data/'

# We will loop through 1 to 8 to check each folder
for i in range(1, 9):
    folder_name = f'function_{i}'
    inputs_path = os.path.join(base_path, folder_name, 'initial_inputs.npy')
    outputs_path = os.path.join(base_path, folder_name, 'initial_outputs.npy')
    
    # Check if files exist before loading
    if os.path.exists(inputs_path) and os.path.exists(outputs_path):
        inputs = np.load(inputs_path)
        outputs = np.load(outputs_path)
        
        print(f"--- {folder_name.upper()} ---")
        print(f"Input Shape:  {inputs.shape}  (Rows: {inputs.shape[0]}, Dimensions: {inputs.shape[1]})")
        print(f"Output Shape: {outputs.shape}")
        # Show the first 2 rows just to see the type of numbers
        print(f"First 2 input rows:\n{inputs[:2]}")
        print("-" * 30 + "\n")
    else:
        print(f"Warning: Data for {folder_name} not found at {inputs_path}")

--- FUNCTION_1 ---
Input Shape:  (10, 2)  (Rows: 10, Dimensions: 2)
Output Shape: (10,)
First 2 input rows:
[[0.31940389 0.76295937]
 [0.57432921 0.8798981 ]]
------------------------------

--- FUNCTION_2 ---
Input Shape:  (10, 2)  (Rows: 10, Dimensions: 2)
Output Shape: (10,)
First 2 input rows:
[[0.66579958 0.12396913]
 [0.87779099 0.7786275 ]]
------------------------------

--- FUNCTION_3 ---
Input Shape:  (15, 3)  (Rows: 15, Dimensions: 3)
Output Shape: (15,)
First 2 input rows:
[[0.17152521 0.34391687 0.2487372 ]
 [0.24211446 0.64407427 0.27243281]]
------------------------------

--- FUNCTION_4 ---
Input Shape:  (30, 4)  (Rows: 30, Dimensions: 4)
Output Shape: (30,)
First 2 input rows:
[[0.89698105 0.72562797 0.17540431 0.70169437]
 [0.8893564  0.49958786 0.53926886 0.50878344]]
------------------------------

--- FUNCTION_5 ---
Input Shape:  (20, 4)  (Rows: 20, Dimensions: 4)
Output Shape: (20,)
First 2 input rows:
[[0.19144708 0.03819337 0.60741781 0.41458414]
 [0.75865295 0.

In [ ]:
import os
import json

# Define the structure
base_dir = "Notebooks"
if not os.path.exists(base_dir):
    os.makedirs(base_dir)

# Basic Notebook Template (JSON format)
template = {
 "cells": [
  {"cell_type": "markdown", "metadata": {}, "source": ["# Optimization for Function X\n", "Goal: Maximise the black-box function using Bayesian Optimization."]},
  {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": [
      "import numpy as np\n",
      "import os\n",
      "# Load Data\n",
      "fn_num = 'X'\n",
      "path = f'../capstone_data/initial_data/function_{fn_num}/'\n",
      "X = np.load(os.path.join(path, 'initial_inputs.npy'))\n",
      "y = np.load(os.path.join(path, 'initial_outputs.npy'))\n",
      "print(f'Function {fn_num} loaded. Input shape:', X.shape)"
  ]}
 ],
 "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}},
 "nbformat": 4, "nbformat_minor": 5
}

# Create 8 notebooks
for i in range(1, 9):
    filename = os.path.join(base_dir, f"{i:02d}_Function_{i}.ipynb")
    # Customise the template for each specific function
    current_temp = json.loads(json.dumps(template).replace('\"X\"', str(i)))
    with open(filename, 'w') as f:
        json.dump(current_temp, f)

print("Success! Check your file navigator for the 'Notebooks' folder.")

In [ ]:
import os

# Define the structure
folders = [
    'notebooks',
    'capstone_data/function_1',
    'capstone_data/function_2',
    'capstone_data/function_3',
    'capstone_data/function_4',
    'capstone_data/function_5',
    'capstone_data/function_6',
    'capstone_data/function_7',
    'capstone_data/function_8',
    'scripts',
    'visuals',
    'documentation/changelogs'
]

files = {
    '.gitignore': ".ipynb_checkpoints/\n__pycache__/\n*.py[cod]\n.DS_Store\n*.zip\n*.log\n.env",
    'README.md': "# 🚀 BBO Capstone Project\n\nWelcome to my Black-Box Optimization research repository.",
    'MODEL_CARD.md': "# 📑 Model Card: CTR-GPBO\n\nDocumentation of the optimization strategy.",
    'DATASHEET.md': "# 📊 Datasheet: BBO Capstone Dataset\n\nDocumentation of the 20-point query history.",
    'scripts/data_manager.py': "# Script to handle .npy updates\nimport numpy as np",
}

# Create Folders
for folder in folders:
    os.makedirs(folder, exist_ok=True)
    print(f"Created folder: {folder}")

# Create Initial Files
for file_path, content in files.items():
    with open(file_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Created file: {file_path}")

print("\n✅ SUCCESS: Your GitHub repository structure is ready!")
print("Now, simply move your .ipynb and .npy files into their respective folders.")